import Head from "next/head";
import Image from "next/image";
import { ContentSection } from "../src/components/contentSection";
import { LeftSideBar } from "../src/components/leftSideBar";
import { RightSideBar } from "../src/components/rightSideBar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <div className={styles.leftSideBarContainer}>
          {" "}
          <LeftSideBar></LeftSideBar>{" "}
        </div>
        <div className={styles.centerContainer}>
          <ContentSection></ContentSection>
        </div>
        <div className={styles.rightSideBarContainer}>
          <RightSideBar></RightSideBar>
        </div>
      </div>
    </div>
  );
}
