import Head from "next/head";
import Image from "next/image";
import { LeftSideBar } from "../src/components/leftSideBar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <div className={styles.leftSideBarContainer}>
          {" "}
          <LeftSideBar></LeftSideBar>{" "}
        </div>
        <div className={styles.centerContainer}>center</div>
        <div className={styles.rightSideBarContainer}>right</div>
      </div>
    </div>
  );
}
