import Head from "next/head";
import Image from "next/image";
import { ContentSection } from "../src/components/contentSection";
import { LeftSideBar } from "../src/components/leftSideBar";
import { RightSideBar } from "../src/components/rightSideBar";
import styles from "../styles/Home.module.css";

export default function Home({ data = [] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>WeFrame Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainContainer}>
        <div className={styles.leftSideBarContainer}>
          {" "}
          <LeftSideBar></LeftSideBar>{" "}
        </div>
        <div className={styles.centerContainer}>
          <ContentSection data={data}></ContentSection>
        </div>
        <div className={styles.rightSideBarContainer}>
          <RightSideBar></RightSideBar>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps(context) {
  function return_url(context) {
    if (process.env.NODE_ENV === "production") {
      return `https://we-frame-task.vercel.app`;
    } else if (process.env.NODE_ENV !== "production") {
      return "http://localhost:3000";
    }
  }
  let url = return_url(context);
  const response = await fetch(`${url}/api/taskData`);
  console.log("response", response);
  if (!response.ok) throw new Error(`Error: ${response.status}`);
  const data = await response.json();
  return { props: { data }, revalidate: 10 };
}
